const TagsList = [
  { title: "Technology", id: 1 },
  { title: "Health", id: 2 },
  { title: "Lifestyle", id: 3 },
  { title: "Finance", id: 4 },
  { title: "Travel", id: 5 },
  { title: "Education", id: 6 },
  { title: "Food", id: 7 },
  { title: "Fitness", id: 8 },
  { title: "Business", id: 9 },
  { title: "Marketing", id: 10 },
  { title: "Science", id: 11 },
  { title: "Personal Development", id: 12 },
  { title: "Fashion", id: 13 },
  { title: "Beauty", id: 14 },
  { title: "DIY", id: 15 },
  { title: "Environment", id: 16 },
  { title: "Sports", id: 17 },
  { title: "Parenting", id: 18 },
  { title: "Photography", id: 19 },
  { title: "Entertainment", id: 20 },
  { title: "Politics", id: 21 },
  { title: "Career", id: 22 },
  { title: "Psychology", id: 23 },
  { title: "Art", id: 24 },
  { title: "Gaming", id: 25 },
  { title: "History", id: 26 },
  { title: "Relationships", id: 27 },
  { title: "Self-Help", id: 28 },
  { title: "Mindfulness", id: 29 },
  { title: "Culture", id: 30 },
  { title: "Startup", id: 31 },
  { title: "Software Development", id: 32 },
  { title: "Web Development", id: 33 },
  { title: "Artificial Intelligence", id: 34 },
  { title: "Machine Learning", id: 35 },
  { title: "Blockchain", id: 36 },
  { title: "Cryptocurrency", id: 37 },
  { title: "Mobile Apps", id: 38 },
  { title: "E-commerce", id: 39 },
  { title: "Productivity", id: 40 },
  { title: "Real Estate", id: 41 },
  { title: "Investing", id: 42 },
  { title: "Digital Marketing", id: 43 },
  { title: "SEO", id: 44 },
  { title: "Social Media", id: 45 },
  { title: "Content Creation", id: 46 },
  { title: "Freelancing", id: 47 },
  { title: "Graphic Design", id: 48 },
  { title: "Writing", id: 49 },
  { title: "Video Production", id: 50 },
  { title: "UX/UI Design", id: 51 },
  { title: "Programming", id: 52 },
  { title: "Technology Trends", id: 53 },
  { title: "Data Science", id: 54 },
  { title: "Cybersecurity", id: 55 },
  { title: "Augmented Reality", id: 56 },
  { title: "Virtual Reality", id: 57 },
  { title: "Robotics", id: 58 },
  { title: "Gadgets", id: 59 },
  { title: "Cloud Computing", id: 60 },
  { title: "SaaS", id: 61 },
  { title: "Work-Life Balance", id: 62 },
  { title: "Mental Health", id: 63 },
  { title: "Nutrition", id: 64 },
  { title: "Wellness", id: 65 },
  { title: "Pet Care", id: 66 },
  { title: "Product Reviews", id: 67 },
  { title: "Home Improvement", id: 68 },
  { title: "Interior Design", id: 69 },
  { title: "Minimalism", id: 70 },
  { title: "Sustainability", id: 71 },
  { title: "Eco-Friendly", id: 72 },
  { title: "Green Technology", id: 73 },
  { title: "Spirituality", id: 74 },
  { title: "Meditation", id: 75 },
  { title: "Yoga", id: 76 },
  { title: "Hiking", id: 77 },
  { title: "Camping", id: 78 },
  { title: "Photography Tips", id: 79 },
  { title: "Film & Cinema", id: 80 },
  { title: "Music", id: 81 },
  { title: "Television", id: 82 },
  { title: "Podcasts", id: 83 },
  { title: "Books", id: 84 },
  { title: "Fiction", id: 85 },
  { title: "Non-Fiction", id: 86 },
  { title: "Poetry", id: 87 },
  { title: "Comics", id: 88 },
  { title: "Anime", id: 89 },
  { title: "Travel Tips", id: 90 },
  { title: "Road Trips", id: 91 },
  { title: "Backpacking", id: 92 },
  { title: "Luxury Travel", id: 93 },
  { title: "Adventure Travel", id: 94 },
  { title: "Skiing", id: 95 },
  { title: "Surfing", id: 96 },
  { title: "Scuba Diving", id: 97 },
  { title: "Mountaineering", id: 98 },
  { title: "Photography Gear", id: 99 },
  { title: "Wedding Planning", id: 100 },
];


export default TagsList;